version: '3.9'

services:

  prometheus:
    image: prom/prometheus:v2.11.1
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
  jmeter:
    image: justb4/jmeter
    volumes:
      - ./jmeter/:/plugins/
      - ./jmeter-test-plans/:/test-plans/
      - ./jmeter-output/:/output/
      - ./jmeter-test-report/:/test-report/
    ports:
      - "9270:9270"
      - "4445:4445"
    command: ["-n", "-t /test-plans/Latencies-Test-Plan.jmx", "-l /output/test.jtl", "-p /plugins/test.properties",
    "-j /output/run_log.log",
    "-o /test-report/",
    "-f",
    "-LDEBUG"]

  sample-app:
    build:
      context: ../sample-app
    ports:
      - "8080:8080"