{
 "title": "Latencies and percentiles",
 "description": "A grafana dashboard to inspect latencies and percentiles of an application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jmeter response times",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(ResponseTime{code=\"200\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Spring response times",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (quantile) (http_server_requests_seconds{uri=\"/latency/sleep/{millis}\"})\n",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Latencies heatmap",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": " sum(increase(http_server_requests_seconds_bucket{uri=\"/latency/sleep/{millis}\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}